### ISSUE TITLE
Trying to contact you about getting efi booting automated with openwrt

### ISSUE THREAD

**Issue by symgryph** [alive4ever/alive4ever.github.io#1]
I noticed your work on the lede forum, and it looks like you had to fork the code. How do I get the lede to build with EFI support?

**Comment by alive4ever** [comment]
Check my abandoned pull request: [lede-project/source/pull#867](https://github.com/lede-project/source/pull/867). You may use it as base for a new pull request, implementing proper uefi automation for not only x86, but also arm/aarch64.

```
git clone https://github.com/lede-project/source # Skip this if you have cloned lede-project source code
cd source
git fetch origin pull/867/head:abandoned-uefi-automation
git checkout abandoned-uefi-automation
make menuconfig
```
Go to target. Select ``x86_64 for uefi based system``.
Go to target images, make sure that ``Install GRUB EFI bootloader`` is checked.
Exit menuconfig, save the configuration and execute ``make`` to start the build process.

**Comment by symgryph** [comment]
By the way thanks for your help. I am very sorry that they didn’t include the patch in lede. P.S. What is the purpose of your own local pull of LEDE? Was it the UEFI stuff?

Thomas

**Comment by alive4ever** [comment]
> your own local pull of LEDE

Do you mean my fork of LEDE source code? So that I can submit pull requests to the project, of course.

Not just UEFI stuff, though. Hard work without rewards yields no motivation.

I'd consider a bounty for adding UEFI automation integrated into lede/openwrt.

**Comment by symgryph** [comment]
Would Gifts of various types of hard count as a bounty? we have loads of x86 stuff floating around mostly industrial spec as well as srm?

Thomas J Munn

**Comment by alive4ever** [comment]
You may also use buildroot instead of lede-project/openwrt and see if buildroot meets your requirements.

Buildroot has configurable support for efi bootloader, with only downside of losing access to openwrt binary packages repository.

**Comment by symgryph** [comment]
We might also send you particular stuff if you have a christmas list of hardware

Thomas J Munn

**Comment by symgryph** [comment]
We might be able to accommodate a hardware bounty in lieu of cash.
Interested?

-- 
-----------------------
Two Wheels Good, Four Wheels Bad
